services:
  smartx-api:
    build:
      context: .
      dockerfile: SmartX.Api/Dockerfile
    container_name: smartx-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  smartx-web:
    build:
      context: .
      dockerfile: SmartX.Web/Dockerfile
    container_name: smartx-web
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SmartXApi__BaseUrl=http://smartx-api:8080/
    depends_on:
      - smartx-api
